### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SMOLKEYS** [MinChat-official/MinChat#1]
Clicking the MinChat button:

```
===============
[Device Brand]: samsung
[Device Model]: SM-G950F
[Display]: evolution_dreamlte-userdebug 13 TQ3A.230705.001.B4 1689011855 release-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: en_US
[Process ID]: 5689
[CPU ABI]: arm64-v8a
[Package Name]: io.anuke.mindustry
[Version Name]: 7-official-145.1
[Version Code]: 30183
[Error Type]: JVM
[Crash Time]: 2023-07-16T18:38:36.629
[Stack Trace]:
kotlin.UninitializedPropertyAccessException: lateinit property client has not been initialized
	at io.minchat.client.MinchatMod.getClient(Minchat.kt:53)
	at io.minchat.client.ui.chat.ChatFragment.updateChatbox(ChatFragment.kt:410)
	at io.minchat.client.ui.chat.ChatFragment.build(ChatFragment.kt:185)
	at io.minchat.client.ui.chat.ChatFragment.build(ChatFragment.kt:26)
	at io.minchat.client.ui.Fragment.apply(Fragment.kt:46)
	at io.minchat.client.MinchatMod.showChatDialog(Minchat.kt:144)
	at io.minchat.client.MinchatMod$2$1$job$1$1.invoke(Minchat.kt:96)
	at io.minchat.client.MinchatMod$2$1$job$1$1.invoke(Minchat.kt:91)
	at com.github.mnemotechnician.mkui.extensions.MiscExtensionsKt.runUi$lambda$0(MiscExtensions.kt:12)
	at com.github.mnemotechnician.mkui.extensions.MiscExtensionsKt.$r8$lambda$IWcaKwnqO5bXSY0KHVp4e407FXA(Unknown Source:0)
	at com.github.mnemotechnician.mkui.extensions.MiscExtensionsKt$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at arc.backend.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:15)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1574)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1273)
```
(Generated by AppsErrorTracking)

**Comment by Mnemotechnician** [comment]
you're using an outdated version of the client
I'mma upload a new release
